name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Display Message
        run: echo "Continuous Integration Pipeline Executed Successfully"

      - name: List Files
        run: ls

      - name: Install HTML Validator
        run: npm install -g html-validate

      - name: Build
        run: |
          mkdir -p build
          cp index.html build/
          html-validate index.html

      - name: List Build Files
        run: ls -la build
